org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=toil_and_trouble
mod.name=Toil and Trouble
mod.group=cc.cassian.cauldrons
mod.version=1.4.5

deps.fabric-loader=0.18.4

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.kaleido=0.3.3+1.3.2

publish.modrinth=67iT29W2
publish.curseforge=1322840
#publish.additionalVersions=