deps.minecraft=1.21.10
deps.fabric-api=0.135.0+1.21.10

deps.parchment=1.21.9:2025.10.05
deps.mojbackward=3

publish.additionalVersions=1.21.9

deps.eiv = 5.1.0+1.21.10
deps.jei = 26.0.0.4
deps.rei = 20.0.811
deps.cloth_config = 19.0.147
deps.modmenu = 16.0.0-rc.1
deps.item_descriptions = 2.5.4+1.21.10
deps.jade=20.0.2+fabric
deps.wthit_version=17.0.4
deps.yacl=3.8.0+1.21.9