mod.mc_dep_fabric=>26.1.2
deps.minecraft=26.2-pre-1
publish.curseforge_minecraft_version=26.1.2

deps.wthit_version=18.0.3
deps.fabric-api=0.149.2+26.2
deps.placeholder_api=2.7.1+1.21.6
deps.item_descriptions=2.7.7+26.2-snapshot-8
deps.jade=21.0.1+neoforge
deps.rrv = 8.2.0+26.2-snapshot-7
deps.jei = 29.4.0.23
deps.modmenu=19.0.0-alpha.1