deps.minecraft=1.21.8
deps.fabric-api=0.136.0+1.21.8
deps.parchment=1.21.8:2025.09.14

publish.additionalVersions=1.21.7

deps.eiv = 3.0.2+1.21.8
deps.jei = 24.0.0.2
deps.rei = 20.0.811
deps.cloth_config = 19.0.147
deps.modmenu = 15.0.0
deps.item_descriptions = 2.5.4+1.21.8
deps.jade=19.3.2+fabric
deps.wthit_version=16.0.1