mod.mc_dep_fabric=>1.21.11
deps.minecraft=26.1-snapshot-7
publish.curseforge_minecraft_version=26.1-snapshot

deps.wthit_version=18.0.3
deps.fabric-api=0.143.4+26.1
deps.placeholder_api=2.7.1+1.21.6
deps.polymer=0.14.2+1.21.9
deps.item_descriptions=2.7.1+26.1-snapshot-7
deps.jade=21.0.1+neoforge
deps.rrv = 6.4.2+26.1-snapshot-9
deps.jei = 27.3.0.14
deps.modmenu=18.0.0-alpha.5